# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-02-07 14:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=10, null=True)),
                ('password', models.CharField(max_length=10, null=True)),
            ],
        ),
    ]
