# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-02-07 14:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vinyfinalapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='users',
            new_name='vinyusers',
        ),
    ]
