# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-02-07 14:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vinyfinalapp', '0002_auto_20170207_2247'),
    ]

    operations = [
        migrations.CreateModel(
            name='collegedb',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=5, null=True)),
                ('Address', models.CharField(max_length=10, null=True)),
            ],
        ),
    ]
