# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-02-07 15:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vinyfinalapp', '0003_collegedb'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vinyusers',
            old_name='password',
            new_name='vpassword',
        ),
        migrations.RenameField(
            model_name='vinyusers',
            old_name='user',
            new_name='vuser',
        ),
    ]
