# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-02-13 15:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vinyfinalapp', '0004_auto_20170207_2302'),
    ]

    operations = [
        migrations.CreateModel(
            name='vinyproducts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vpid', models.CharField(max_length=10, null=True)),
                ('vpname', models.CharField(max_length=20, null=True)),
                ('vptype', models.CharField(max_length=10, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='collegedb',
        ),
    ]
