# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-02-14 04:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vinyfinalapp', '0006_vinyitems'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vinyitems',
            name='vprice',
            field=models.IntegerField(default=0),
        ),
    ]
