# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-02-14 07:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vinyfinalapp', '0008_auto_20170214_1224'),
    ]

    operations = [
        migrations.CreateModel(
            name='vinyaddcart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vpid', models.CharField(max_length=10, null=True)),
                ('vitemid', models.CharField(max_length=20, null=True)),
                ('vdesc', models.CharField(max_length=50, null=True)),
                ('vprice', models.FloatField(default=0.0)),
                ('vstock', models.CharField(default='true', max_length=10)),
                ('quantity', models.IntegerField(default=1)),
            ],
        ),
    ]
